
package Banking;


import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class AllUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form AllUsers
     */
    public AllUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("All Users");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        l1.setText("All Users");
        getContentPane().add(l1);
        l1.setBounds(440, 20, 140, 35);

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Name", "Gender", "Date of Birth", "Phone No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCellSelectionEnabled(true);
        table.setEnabled(false);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 990, 650);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/users.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 90, 70);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            
            try {
                String q = "Select * from user_info";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) table.getModel();
                String user_name, age, gender, dob, phno, address;
                ResultSet myresult = mystatement.executeQuery();
                
                if (myresult.next()) {
                    
                    mymodel.setRowCount(0);
                    do {
                        user_name = myresult.getString("username");
                        age = myresult.getString("name");
                        gender = myresult.getString("gender");
                        dob = myresult.getString("dob");
                        phno = myresult.getString("phno");
                        address = myresult.getString("address");
                        mymodel.addRow(new Object[]{user_name, age, gender, dob, phno, address});
                    } while (myresult.next());
                } else {
                    
                    JOptionPane.showMessageDialog(rootPane, "No Record Found.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
