
package Banking;


import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class BalanceSheet extends javax.swing.JInternalFrame {
    
    private void fillTable(String str) {
        
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            
            try {
                
                PreparedStatement mystatement = myconnection.prepareStatement(str);
                DefaultTableModel mymodel = (DefaultTableModel) JTable1.getModel();
                String accountno, mode, date, d_w;
                int amount = 0, balance = 0;
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    mymodel.setRowCount(0);
                    do {
                        
                        accountno = myresult.getString("accountno");
                        mode = myresult.getString("mode");
                        balance = myresult.getInt("balance");
                        amount = myresult.getInt("amount");
                        date = myresult.getString("date");
                        d_w = myresult.getString("d_w");
                        
                        if (d_w.equalsIgnoreCase("debit")) {
                            mymodel.addRow(new Object[]{accountno, date, mode, "", amount, (balance - amount)});
                        } else if (d_w.equalsIgnoreCase("deposit")) {
                            mymodel.addRow(new Object[]{accountno, date, mode, amount, "", (balance + amount)});
                        }
                    } while (myresult.next());
                } else {
                    
                    JOptionPane.showMessageDialog(rootPane, "No Record Found.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
        
        
    }

    /**
     * Creates new form BalanceSheet
     */
    public BalanceSheet() {
        initComponents();
        
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                combobox1.addItem("0" + a);
            } else {
                combobox1.addItem("" + a);
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                combobox2.addItem("0" + a);
            } else {
                combobox2.addItem("" + a);
            }
        }
        for (int a = 2000; a <= 2050; a++) {
            combobox3.addItem("" + a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        combobox1 = new javax.swing.JComboBox();
        combobox2 = new javax.swing.JComboBox();
        combobox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Balance Sheet");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Balance Sheet");
        getContentPane().add(l1);
        l1.setBounds(430, 50, 220, 40);

        btn1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn1.setText("Show");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(830, 160, 91, 29);

        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No", "Date", "Mode", "Deposit", "Debit", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable1.setEnabled(false);
        jScrollPane1.setViewportView(JTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(19, 230, 980, 480);

        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(combobox1);
        combobox1.setBounds(560, 160, 67, 26);

        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(combobox2);
        combobox2.setBounds(640, 160, 80, 26);

        combobox3.setMaximumRowCount(10);
        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox3ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox3);
        combobox3.setBounds(730, 160, 76, 26);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 160, 250, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 160, 100, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(510, 150, 20, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/notepad.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 30, 70, 70);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (combobox1.getSelectedIndex() == 0 && combobox3.getSelectedIndex() == 0 && combobox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Select Proper Date!!");
        } else {
            jTextField1.setText("");
            String qry = "select * from transaction where date='" + combobox3.getSelectedItem() + "-" + combobox2.getSelectedItem() + "-" + combobox1.getSelectedItem() + "'";
            fillTable(qry);
        }
        
    }//GEN-LAST:event_btn1ActionPerformed
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated
    
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:

    if (jTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Enter Account Number first!!");
    } else {
        combobox1.setSelectedIndex(0);
        combobox2.setSelectedIndex(0);
        combobox3.setSelectedIndex(0);
        
        String qry = "select * from transaction where accountno='" + jTextField1.getText() + "'";
        fillTable(qry);
    }
    
}//GEN-LAST:event_jButton1ActionPerformed

    private void combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable1;
    private javax.swing.JButton btn1;
    private javax.swing.JComboBox combobox1;
    private javax.swing.JComboBox combobox2;
    private javax.swing.JComboBox combobox3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
