
package Banking;


import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;

public class DraftForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DraftForm
     */
    public DraftForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateLabel = new javax.swing.JLabel();
        DateLabelShow = new javax.swing.JLabel();
        FavourofLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FavourofText = new javax.swing.JTextPane();
        AccountNoLabel = new javax.swing.JLabel();
        AccountLabel = new javax.swing.JTextField();
        AmontLabel = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        DraftNoLabel = new javax.swing.JLabel();
        DraftTextLabel = new javax.swing.JTextField();
        DraftFormLabel = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Draft Form");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        DateLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        DateLabel.setText("Date");
        getContentPane().add(DateLabel);
        DateLabel.setBounds(190, 230, 120, 30);

        DateLabelShow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLabelShow.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DateLabelShow);
        DateLabelShow.setBounds(470, 230, 290, 30);

        FavourofLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        FavourofLabel.setText("In Favour of");
        getContentPane().add(FavourofLabel);
        FavourofLabel.setBounds(190, 350, 140, 30);

        FavourofText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(FavourofText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 340, 290, 150);

        AccountNoLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AccountNoLabel.setText("Account No.");
        getContentPane().add(AccountNoLabel);
        AccountNoLabel.setBounds(190, 520, 190, 30);

        AccountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(AccountLabel);
        AccountLabel.setBounds(470, 520, 290, 30);

        AmontLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AmontLabel.setText("Amount");
        getContentPane().add(AmontLabel);
        AmontLabel.setBounds(190, 580, 140, 30);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(470, 580, 290, 30);

        SaveButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        SaveButton.setText("Save Draft");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton);
        SaveButton.setBounds(550, 650, 140, 40);

        DraftNoLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        DraftNoLabel.setText("Draft Number");
        getContentPane().add(DraftNoLabel);
        DraftNoLabel.setBounds(190, 280, 160, 30);

        DraftTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(DraftTextLabel);
        DraftTextLabel.setBounds(470, 280, 290, 30);

        DraftFormLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        DraftFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DraftFormLabel.setText("Draft Form");
        getContentPane().add(DraftFormLabel);
        DraftFormLabel.setBounds(540, 60, 180, 90);

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/cheque.png"))); // NOI18N
        getContentPane().add(Image);
        Image.setBounds(320, 30, 200, 160);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        java.util.Date obj = new java.util.Date();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String currentdate = dateformat.format(obj);
        DateLabelShow.setText(currentdate);
    }//GEN-LAST:event_formInternalFrameActivated

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "insert into draft_info values(?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, DraftTextLabel.getText());
                mystatement.setString(2, DateLabelShow.getText());
                mystatement.setString(3, FavourofText.getText());

                mystatement.setString(4, AccountLabel.getText());
                mystatement.setString(5, t2.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Draft Saved Successfully");

                DraftTextLabel.setText("");

                FavourofText.setText(null);

                AccountLabel.setText(null);
                t2.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_SaveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountLabel;
    private javax.swing.JLabel AccountNoLabel;
    private javax.swing.JLabel AmontLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DateLabelShow;
    private javax.swing.JLabel DraftFormLabel;
    private javax.swing.JLabel DraftNoLabel;
    private javax.swing.JTextField DraftTextLabel;
    private javax.swing.JLabel FavourofLabel;
    private javax.swing.JTextPane FavourofText;
    private javax.swing.JLabel Image;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
