
package Banking;


import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;

public class FDForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FDForm
     */
    public FDForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("FD Form");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l2.setText("Account No");
        getContentPane().add(l2);
        l2.setBounds(210, 340, 170, 20);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(530, 330, 290, 30);

        l3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l3.setText("Mode ");
        getContentPane().add(l3);
        l3.setBounds(210, 400, 160, 20);

        combobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Mode", "Self", "Child" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        getContentPane().add(combobox);
        combobox.setBounds(530, 390, 290, 30);

        l5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l5.setText("Rupees");
        getContentPane().add(l5);
        l5.setBounds(210, 460, 140, 30);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(530, 450, 290, 30);

        l6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l6.setText("Period (yr)");
        getContentPane().add(l6);
        l6.setBounds(210, 510, 130, 30);

        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(530, 510, 290, 30);

        l7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l7.setText("Interest %");
        getContentPane().add(l7);
        l7.setBounds(210, 570, 120, 30);

        l9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        l9.setText("Date of Issue");
        getContentPane().add(l9);
        l9.setBounds(210, 260, 170, 30);

        l10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l10);
        l10.setBounds(530, 260, 290, 30);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn1.setText("Save");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(450, 660, 130, 30);

        t4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(530, 570, 290, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/safebox.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 40, 150, 140);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Fixed Deposit");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 100, 210, 26);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
        java.util.Date obj = new java.util.Date();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String currentdate = dateformat.format(obj);
        l10.setText(currentdate);
    }//GEN-LAST:event_formInternalFrameActivated

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here: 
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "insert into fd_info(accountno,mode,rupees,period,interest,date) values(?,?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t1.getText());
                mystatement.setString(2, combobox.getSelectedItem().toString());
                mystatement.setString(3, t2.getText());
                mystatement.setString(4, t3.getText());
                mystatement.setString(5, t4.getText());
                mystatement.setString(6, l10.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Save Successfully");
                t1.setText(null);
                combobox.setSelectedIndex(0);
                t2.setText(null);
                t3.setText(null);
                t4.setText(null);
            } catch (Exception e) {
                //   JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JComboBox combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
