
package Banking;


import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;

;

public class NewAccount extends javax.swing.JInternalFrame {

   
    JFileChooser fc;
    File myfile;
    String pic = "";

    public NewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        formattedtext = new javax.swing.JFormattedTextField();
        combobox1 = new javax.swing.JComboBox();
        combobox2 = new javax.swing.JComboBox();
        combobox3 = new javax.swing.JComboBox();
        t3 = new javax.swing.JTextField();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l13 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        l14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        l15 = new javax.swing.JLabel();
        combobox4 = new javax.swing.JComboBox();
        t5 = new javax.swing.JTextField();
        l16 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setTitle("New Account");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        l1.setText("Customer Information Form");
        getContentPane().add(l1);
        l1.setBounds(120, 40, 400, 34);

        l3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l3.setText("Account No");
        getContentPane().add(l3);
        l3.setBounds(30, 170, 130, 20);

        l4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l4);
        l4.setBounds(170, 170, 220, 30);

        l5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l5.setText("Name");
        getContentPane().add(l5);
        l5.setBounds(30, 210, 150, 20);
        getContentPane().add(t1);
        t1.setBounds(170, 210, 220, 30);

        l7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l7.setText("Gender");
        getContentPane().add(l7);
        l7.setBounds(30, 530, 130, 21);

        buttonGroup1.add(r1);
        r1.setText("Male");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(200, 530, 70, 25);

        buttonGroup1.add(r2);
        r2.setText("Female");
        getContentPane().add(r2);
        r2.setBounds(290, 530, 80, 25);

        l8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l8.setText("Date of Birth");
        getContentPane().add(l8);
        l8.setBounds(30, 240, 120, 30);

        l9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l9.setText("Phone No.");
        getContentPane().add(l9);
        l9.setBounds(30, 290, 120, 21);

        l10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l10.setText("Marital Status");
        getContentPane().add(l10);
        l10.setBounds(30, 560, 140, 20);

        buttonGroup2.add(r3);
        r3.setText("Married");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(200, 560, 80, 25);

        buttonGroup2.add(r4);
        r4.setText("Unmarried");
        getContentPane().add(r4);
        r4.setBounds(290, 560, 90, 25);

        try {
            formattedtext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(formattedtext);
        formattedtext.setBounds(170, 290, 230, 30);

        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox1);
        combobox1.setBounds(160, 250, 60, 30);

        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(combobox2);
        combobox2.setBounds(230, 250, 91, 30);

        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        getContentPane().add(combobox3);
        combobox3.setBounds(330, 250, 72, 30);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(670, 520, 230, 30);

        l11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l11.setText("Father Name");
        getContentPane().add(l11);
        l11.setBounds(520, 520, 150, 20);

        l12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l12.setText("Mother Name");
        getContentPane().add(l12);
        l12.setBounds(520, 480, 150, 20);
        getContentPane().add(t4);
        t4.setBounds(670, 480, 230, 30);

        l13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l13.setText("Address");
        getContentPane().add(l13);
        l13.setBounds(30, 330, 130, 20);

        btn2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn2.setText("Save");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(390, 650, 200, 30);

        l14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l14.setText("District");
        getContentPane().add(l14);
        l14.setBounds(30, 420, 130, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(textpane);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(170, 330, 230, 100);

        l15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l15.setText("State");
        getContentPane().add(l15);
        l15.setBounds(30, 470, 120, 20);

        combobox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select State" }));
        combobox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox4ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox4);
        combobox4.setBounds(170, 480, 230, 30);
        getContentPane().add(t5);
        t5.setBounds(170, 440, 230, 30);

        l16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l16.setText("Balance");
        getContentPane().add(l16);
        l16.setBounds(520, 560, 130, 30);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(670, 560, 230, 30);

        l17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l17.setText("Current Date");
        getContentPane().add(l17);
        l17.setBounds(30, 110, 110, 30);

        l18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l18);
        l18.setBounds(180, 110, 210, 30);

        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l2);
        l2.setBounds(520, 90, 420, 340);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn1.setText("Upload Pic");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(680, 440, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/add-user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 70, 70);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        if (r1.isSelected()) {
            r1.setText("Male");
        } else if (r2.isSelected()) {
            r2.setText("Female");
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
        if (r3.isSelected()) {
            r3.setText("Married");
        } else if (r4.isSelected()) {
            r4.setText("Unmarried");
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String filename = "";

        if (myfile != null) {
            filename = "Images\\" + new Date().getTime() + "_" + myfile.getName();//Date.getTime() added for unique file name.
            int i;
            FileInputStream rd = null;
            FileOutputStream outs = null;
            try {

                rd = new FileInputStream(myfile);
                outs = new FileOutputStream(filename);//writing the new file in 'Images' folder, in the project

                byte[] b = new byte[2048];
                while ((i = rd.read(b)) > 0) {
                    outs.write(b, 0, i);

                }
                JOptionPane.showMessageDialog(rootPane, "File saved");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
            } finally {
                try {
                    rd.close();
                    outs.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
                }
            }
        } else {
            filename = "Images\\mypic.png";

        }
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = (Connection) DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "insert into customer_info values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, filename);
                mystatement.setString(2, l4.getText());

                mystatement.setString(3, t1.getText());

                if (r1.isSelected()) {
                    mystatement.setString(4, "Male");
                } else if (r2.isSelected()) {
                    mystatement.setString(4, "Female");
                }
                String dob = combobox3.getSelectedItem() + "-" + combobox2.getSelectedItem() + "-" + combobox1.getSelectedItem();
                mystatement.setString(5, dob);
                mystatement.setString(6, formattedtext.getText());
                if (r3.isSelected()) {
                    mystatement.setString(7, "Married");
                } else if (r4.isSelected()) {
                    mystatement.setString(7, "Unmarried");
                }
                mystatement.setString(8, t3.getText());
                mystatement.setString(9, t4.getText());
                mystatement.setString(10, textpane.getText());
                mystatement.setString(11, t5.getText());
                mystatement.setString(12, combobox4.getSelectedItem().toString());
                mystatement.setString(13, t6.getText());
                mystatement.setString(14, l18.getText());

                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Save Successfully");
                generateaccountnumber();
                t1.setText(null);


                combobox1.setSelectedIndex(0);
                combobox2.setSelectedIndex(0);
                combobox3.setSelectedIndex(0);
                formattedtext.setText(null);
                buttonGroup1.clearSelection();
                buttonGroup2.clearSelection();
                t3.setText(null);
                t4.setText(null);
                textpane.setText(null);
                t5.setText(null);
                combobox4.setSelectedIndex(0);
                t6.setText(null);
                l2.setText(null);
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void combobox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox4ActionPerformed
    public void generateaccountnumber() {
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = (Connection) DriverManager.getConnection(path + place, "root", "");
                String q = "Select accountno from customer_info order by accountno DESC";
                PreparedStatement mystatement = (PreparedStatement) myconnection.prepareStatement(q);
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    long oldno = Long.parseLong(myresult.getString("accountno"));
                    long newno = oldno + 1;
                    l4.setText("" + newno);
                } else {
                    l4.setText("1103090278020001");
                }
                java.util.Date obj = new java.util.Date();
                SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
                String currentdate = dateformat.format(obj);
                l18.setText(currentdate);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:

        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        generateaccountnumber();
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                combobox1.addItem("0" + a);
            } else {
                combobox1.addItem("" + a);
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                combobox2.addItem("0" + a);
            } else {
                combobox2.addItem("" + a);
            }
        }
        for (int a = 1948; a <= 2000; a++) {

            combobox3.addItem("" + a);
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = (Connection) DriverManager.getConnection(path + place, "root", "");
            String q = "Select * from states";
            PreparedStatement mystatement = (PreparedStatement) myconnection.prepareStatement(q);
            ResultSet myresult = mystatement.executeQuery();
            while (myresult.next()) {
                combobox4.addItem(myresult.getString("statename"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc = new JFileChooser();

        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                int pos = f.getName().lastIndexOf('.');
                if (pos == -1) {
                    return false;
                } else {
                    String extention = f.getName().substring(pos + 1);//saving the extension
                    String str[] = {"gif", "png", "jpg", "jpeg"};//allowed extentions
                    for (String allwd : str) {

                        if (extention.equalsIgnoreCase(allwd)) {
                            return true;
                        }
                    }
                    return false;
                }

            }

            @Override
            public String getDescription() {

                return "";
            }
        });
        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            myfile = fc.getSelectedFile();

            try {
                l2.setIcon(new ImageIcon(ImageIO.read(myfile)));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Error");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox combobox1;
    private javax.swing.JComboBox combobox2;
    private javax.swing.JComboBox combobox3;
    private javax.swing.JComboBox combobox4;
    private javax.swing.JFormattedTextField formattedtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextPane textpane;
    // End of variables declaration//GEN-END:variables
}
