
package Banking;


import java.sql.*;
import javax.swing.*;

public class UpdateUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form update2
     */
    public UpdateUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        l5 = new javax.swing.JLabel();
        combobox1 = new javax.swing.JComboBox();
        combobox2 = new javax.swing.JComboBox();
        combobox3 = new javax.swing.JComboBox();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        btn2 = new javax.swing.JButton();
        formattedtext = new javax.swing.JFormattedTextField();
        btn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Search/Update User");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        l1.setText("Update User");
        getContentPane().add(l1);
        l1.setBounds(440, 70, 210, 60);

        l2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l2.setText("User Name");
        getContentPane().add(l2);
        l2.setBounds(260, 220, 140, 20);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(440, 220, 210, 30);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn1.setText("Details");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(750, 220, 90, 30);

        l3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l3.setText("Name");
        getContentPane().add(l3);
        l3.setBounds(260, 270, 90, 20);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(440, 260, 210, 30);

        l4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l4.setText("Gender");
        getContentPane().add(l4);
        l4.setBounds(260, 300, 160, 29);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r1.setText("Male");
        getContentPane().add(r1);
        r1.setBounds(440, 300, 80, 25);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r2.setText("Female");
        getContentPane().add(r2);
        r2.setBounds(560, 300, 90, 25);

        l5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l5.setText("Date of Birth");
        getContentPane().add(l5);
        l5.setBounds(260, 350, 140, 25);

        combobox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(combobox1);
        combobox1.setBounds(440, 350, 65, 30);

        combobox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(combobox2);
        combobox2.setBounds(510, 350, 92, 30);

        combobox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox3ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox3);
        combobox3.setBounds(610, 350, 75, 30);

        l6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l6.setText("Phone");
        getContentPane().add(l6);
        l6.setBounds(260, 390, 100, 23);

        l7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l7.setText("Address");
        getContentPane().add(l7);
        l7.setBounds(260, 440, 100, 23);

        textpane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(textpane);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(440, 440, 210, 130);

        btn2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn2.setText("Update");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(350, 630, 120, 30);

        try {
            formattedtext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(formattedtext);
        formattedtext.setBounds(440, 390, 210, 30);

        btn3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn3.setText("Delete");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(530, 630, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/users.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 70, 80, 60);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from user_info where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t1.getText());
                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {

                    t2.setText(myresult.getString("name"));
                    if (myresult.getString("gender").equals("Male")) {
                        r1.setSelected(true);
                    } else if (myresult.getString("gender").equals("Female")) {
                        r2.setSelected(true);
                    }
                    String dob1 = myresult.getString("dob");
                    String a[] = dob1.split("-");
                    combobox1.setSelectedItem(a[2]);
                    combobox2.setSelectedItem(a[1]);
                    combobox3.setSelectedItem(a[0]);
                    formattedtext.setText(myresult.getString("phno"));
                    textpane.setText(myresult.getString("address"));
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No record");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "Update user_info set name=?,gender=?,dob=?,phno=?,address=? where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t2.getText());
                if (r1.isSelected()) {
                    mystatement.setString(2, "Male");
                } else if (r2.isSelected()) {
                    mystatement.setString(2, "Female");
                }
                String dob = combobox3.getSelectedItem() + "-" + combobox2.getSelectedItem() + "-" + combobox1.getSelectedItem();
                mystatement.setString(3, dob);

                mystatement.setString(4, formattedtext.getText());
                mystatement.setString(5, textpane.getText());
                mystatement.setString(6, t1.getText());
                mystatement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Updated Successfully");
                t1.setText(null);
                t2.setText(null);
                buttonGroup1.clearSelection();

                combobox1.setSelectedIndex(0);
                combobox2.setSelectedIndex(0);
                combobox3.setSelectedIndex(0);
                formattedtext.setText(null);
                textpane.setText(null);
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                combobox1.addItem("0" + a);
            } else {
                combobox1.addItem("" + a);
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                combobox2.addItem("0" + a);
            } else {
                combobox2.addItem("" + a);
            }
        }
        for (int a = 1948; a <= 2000; a++) {
            combobox3.addItem("" + a);
        }
    }//GEN-LAST:event_formInternalFrameActivated

private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
    // TODO add your handling code here:
    String path = "jdbc:mysql://localhost/";
    String place = "bankingdb";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection myconnection = DriverManager.getConnection(path + place, "root", "");
        try {
            String q = "Delete from create_user where username=?";
            PreparedStatement mystatement = myconnection.prepareStatement(q);
            mystatement.setString(1, t1.getText());
            int n = mystatement.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");

                t1.setText(null);
                t2.setText(null);
                buttonGroup1.clearSelection();

                combobox1.setSelectedIndex(0);
                combobox2.setSelectedIndex(0);
                combobox3.setSelectedIndex(0);
                formattedtext.setText(null);
                textpane.setText(null);

            }

            mystatement.close();
            myconnection.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
    }
}//GEN-LAST:event_btn3ActionPerformed

    private void combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combobox1;
    private javax.swing.JComboBox combobox2;
    private javax.swing.JComboBox combobox3;
    private javax.swing.JFormattedTextField formattedtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextPane textpane;
    // End of variables declaration//GEN-END:variables
}
