
package Banking;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

public class UpdateAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form update1
     */
    String old;

    public UpdateAccount() {
        initComponents();
    }
    JFileChooser fc;
    File myfile;
    String pic = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        formattedtext = new javax.swing.JFormattedTextField();
        combobox1 = new javax.swing.JComboBox();
        combobox2 = new javax.swing.JComboBox();
        combobox3 = new javax.swing.JComboBox();
        t4 = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l12 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        l13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        l14 = new javax.swing.JLabel();
        combobox4 = new javax.swing.JComboBox();
        t6 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Update Customer Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        l1.setText("Updation Form");
        getContentPane().add(l1);
        l1.setBounds(230, 20, 230, 34);

        l3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l3.setText("Account No.");
        getContentPane().add(l3);
        l3.setBounds(20, 100, 130, 20);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(140, 100, 200, 28);

        l4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l4.setText("Name");
        getContentPane().add(l4);
        l4.setBounds(20, 140, 150, 20);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(140, 140, 200, 30);

        l6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l6.setText("Gender");
        getContentPane().add(l6);
        l6.setBounds(20, 570, 90, 30);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r1.setText("Male");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(150, 570, 90, 30);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r2.setText("Female");
        getContentPane().add(r2);
        r2.setBounds(260, 570, 100, 30);

        l7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l7.setText("Date of Birth");
        getContentPane().add(l7);
        l7.setBounds(20, 180, 120, 30);

        l8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l8.setText("Phone No.");
        getContentPane().add(l8);
        l8.setBounds(20, 300, 110, 30);

        l9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l9.setText("Marital Status");
        getContentPane().add(l9);
        l9.setBounds(20, 610, 140, 30);

        buttonGroup2.add(r3);
        r3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r3.setText("Married");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(150, 610, 110, 25);

        buttonGroup2.add(r4);
        r4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r4.setText("Unmarried");
        getContentPane().add(r4);
        r4.setBounds(260, 610, 110, 25);

        try {
            formattedtext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedtextActionPerformed(evt);
            }
        });
        getContentPane().add(formattedtext);
        formattedtext.setBounds(140, 300, 190, 30);

        combobox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox1);
        combobox1.setBounds(140, 180, 60, 30);

        combobox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(combobox2);
        combobox2.setBounds(210, 180, 70, 30);

        combobox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox3ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox3);
        combobox3.setBounds(290, 180, 70, 30);

        t4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(140, 260, 190, 30);

        l10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l10.setText("Father Name");
        getContentPane().add(l10);
        l10.setBounds(20, 260, 150, 30);

        l11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l11.setText("Mother Name");
        getContentPane().add(l11);
        l11.setBounds(20, 220, 130, 30);

        t5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t5);
        t5.setBounds(140, 220, 190, 30);

        l12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l12.setText("Address");
        getContentPane().add(l12);
        l12.setBounds(20, 340, 130, 20);

        btn2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn2.setText("Update");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(180, 670, 150, 30);

        l13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l13.setText("District");
        getContentPane().add(l13);
        l13.setBounds(20, 480, 100, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textpane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(textpane);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 340, 230, 120);

        l14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l14.setText("State");
        getContentPane().add(l14);
        l14.setBounds(20, 520, 100, 30);

        combobox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select State" }));
        combobox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox4ActionPerformed(evt);
            }
        });
        getContentPane().add(combobox4);
        combobox4.setBounds(140, 520, 190, 30);

        t6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t6);
        t6.setBounds(140, 480, 190, 30);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn1.setText("Details");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(350, 100, 130, 30);

        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(l2);
        l2.setBounds(500, 350, 500, 350);

        btn3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn3.setText("Upload Pic");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(10, 670, 150, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setMnemonic('s');
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 140, 130, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acc Num", "Name", "Phone", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 10, 500, 320);

        btn4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn4.setText("Delete");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(340, 670, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 50, 50);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        if (r1.isSelected()) {
            r1.setText("Male");
        } else if (r2.isSelected()) {
            r2.setText("Female");
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
        if (r3.isSelected()) {
            r3.setText("Married");
        } else if (r4.isSelected()) {
            r4.setText("Unmarried");
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String filename = "";

        if (myfile != null) {
            filename = "Images\\" + new java.util.Date().getTime() + "_" + myfile.getName();//Date.getTime() added for unique file name.
            int i;
            FileInputStream rd = null;
            FileOutputStream outs = null;
            try {

                rd = new FileInputStream(myfile);
                outs = new FileOutputStream(filename);//writing the new file in 'Images' folder, in the project

                byte[] b = new byte[2048];
                while ((i = rd.read(b)) > 0) {
                    outs.write(b, 0, i);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
            } finally {
                try {
                    rd.close();
                    outs.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
                }
            }
        } else {
            filename = old;

        }
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "Update customer_info set name=?,gender=?,dob=?,phno=?,maritalstatus=?,fname=?,mname=?,address=?,district_name=?,state_name=?,pic=? where accountno=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);

                mystatement.setString(1, t2.getText());

                if (r1.isSelected()) {
                    mystatement.setString(2, "Male");
                } else if (r2.isSelected()) {
                    mystatement.setString(2, "Female");
                }
                String dob = combobox3.getSelectedItem() + "-" + combobox2.getSelectedItem() + "-" + combobox1.getSelectedItem();
                mystatement.setString(3, dob);
                mystatement.setString(4, formattedtext.getText());
                if (r3.isSelected()) {
                    mystatement.setString(5, "Married");
                } else if (r4.isSelected()) {
                    mystatement.setString(5, "Unmarried");
                }
                mystatement.setString(6, t4.getText());
                mystatement.setString(7, t5.getText());
                mystatement.setString(8, textpane.getText());
                mystatement.setString(9, t6.getText());
                String state = combobox4.getSelectedItem().toString();
                mystatement.setString(10, state);
                mystatement.setString(11, filename);
                mystatement.setString(12, t1.getText());
                mystatement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Updated Successfully");
                t2.setText("");
                jButton1ActionPerformed(null);

                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void combobox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox4ActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_combobox4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "Select * from customer_info where accountno=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t1.getText());
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    old = myresult.getString("pic");
                    l2.setIcon(new ImageIcon(ImageIO.read(new File(old))));
                    t2.setText(myresult.getString("name"));

                    if (myresult.getString("gender").equals("Male")) {
                        r1.setSelected(true);
                    } else if (myresult.getString("gender").equals("Female")) {
                        r2.setSelected(true);
                    }
                    String dob1 = myresult.getString("dob");
                    String a[] = dob1.split("-");
                    combobox1.setSelectedItem(a[2]);
                    combobox2.setSelectedItem(a[1]);
                    combobox3.setSelectedItem(a[0]);
                    formattedtext.setText(myresult.getString("phno"));
                    if (myresult.getString("maritalstatus").equals("Married")) {
                        r3.setSelected(true);
                    } else if (myresult.getString("maritalstatus").equals("Unmarried")) {
                        r4.setSelected(true);
                    }
                    t4.setText(myresult.getString("fname"));
                    t5.setText(myresult.getString("mname"));
                    textpane.setText(myresult.getString("address"));
                    t6.setText(myresult.getString("district_name"));
                    combobox4.setSelectedItem(myresult.getString("state_name"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                combobox1.addItem("0" + a);
            } else {
                combobox1.addItem("" + a);
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                combobox2.addItem("0" + a);
            } else {
                combobox2.addItem("" + a);
            }
        }
        for (int a = 1948; a <= 2000; a++) {
            combobox3.addItem("" + a);
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String q = "Select * from states";
            PreparedStatement mystatement = myconnection.prepareStatement(q);
            ResultSet myresult = mystatement.executeQuery();
            while (myresult.next()) {
                combobox4.addItem(myresult.getString("statename"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc = new JFileChooser();

        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                int pos = f.getName().lastIndexOf('.');
                if (pos == -1) {
                    return false;
                } else {
                    String extention = f.getName().substring(pos + 1);//saving the extension
                    String str[] = {"gif", "png", "jpg", "jpeg"};//allowed extentions
                    for (String allwd : str) {

                        if (extention.equalsIgnoreCase(allwd)) {
                            return true;
                        }
                    }
                    return false;
                }

            }

            @Override
            public String getDescription() {

                return "";
            }
        });
        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            myfile = fc.getSelectedFile();

            try {
                l2.setIcon(new ImageIcon(ImageIO.read(myfile)));
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Error");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "Select * from customer_info where name like '%" + t2.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    tbl.setRowCount(0);

                    do {
                        tbl.addRow(new Object[]{myresult.getString("accountno"), myresult.getString("name"), myresult.getString("phno"), myresult.getString("address")});
                    } while (myresult.next());


                    l2.setIcon(null);
                    t1.setText("");


                    combobox1.setSelectedIndex(0);
                    combobox2.setSelectedIndex(0);
                    combobox3.setSelectedIndex(0);
                    formattedtext.setText("");
                    buttonGroup1.clearSelection();
                    buttonGroup2.clearSelection();
                    t4.setText("");
                    t5.setText("");
                    textpane.setText("");
                    t6.setText("");
                    combobox4.setSelectedIndex(0);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    String acc = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    t1.setText(acc);
    btn1ActionPerformed(null);

}//GEN-LAST:event_jTable1MouseClicked

private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
    // TODO add your handling code here:
    String path = "jdbc:mysql://localhost/";
    String place = "bankingdb";
    int n = JOptionPane.showConfirmDialog(textpane, "Are you sure want to delete informnation of account : " + t1.getText() + " ?");
    if (n == 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "Delete from customer_info where accountno=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t1.getText());
                int a = mystatement.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Deleted successfully");
                }
                t2.setText("");
                jButton1ActionPerformed(null);
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }
}//GEN-LAST:event_btn4ActionPerformed

    private void formattedtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedtextActionPerformed

    private void combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox combobox1;
    private javax.swing.JComboBox combobox2;
    private javax.swing.JComboBox combobox3;
    private javax.swing.JComboBox combobox4;
    private javax.swing.JFormattedTextField formattedtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextPane textpane;
    // End of variables declaration//GEN-END:variables
}
