
package Banking;

import java.sql.Connection;
import java.sql.DriverManager;


import java.sql.*;
import javax.swing.*;

public class UserInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserInfo
     */
    public UserInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        combobox1 = new javax.swing.JComboBox();
        combobox2 = new javax.swing.JComboBox();
        combobox3 = new javax.swing.JComboBox();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        btn1 = new javax.swing.JButton();
        formattedtext = new javax.swing.JFormattedTextField();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Create User");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/account.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        l1.setText("User Information");
        getContentPane().add(l1);
        l1.setBounds(410, 60, 250, 40);

        l2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l2.setText("Password");
        getContentPane().add(l2);
        l2.setBounds(630, 290, 93, 30);
        getContentPane().add(t1);
        t1.setBounds(770, 220, 180, 29);

        l4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l4.setText("Gender");
        getContentPane().add(l4);
        l4.setBounds(80, 260, 110, 29);

        buttonGroup1.add(r1);
        r1.setText("Male");
        getContentPane().add(r1);
        r1.setBounds(290, 260, 70, 25);

        buttonGroup1.add(r2);
        r2.setText("Female");
        getContentPane().add(r2);
        r2.setBounds(370, 260, 90, 25);

        l3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l3.setText("Name");
        getContentPane().add(l3);
        l3.setBounds(80, 210, 90, 30);
        getContentPane().add(t2);
        t2.setBounds(290, 210, 220, 29);

        l5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l5.setText("Date of Birth");
        getContentPane().add(l5);
        l5.setBounds(80, 310, 120, 25);

        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(combobox1);
        combobox1.setBounds(290, 300, 60, 30);

        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(combobox2);
        combobox2.setBounds(360, 300, 70, 30);

        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        getContentPane().add(combobox3);
        combobox3.setBounds(440, 300, 80, 30);

        l6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l6.setText("Phone");
        getContentPane().add(l6);
        l6.setBounds(80, 350, 110, 23);

        l7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l7.setText("Address");
        getContentPane().add(l7);
        l7.setBounds(80, 420, 110, 23);

        jScrollPane1.setViewportView(textpane);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 410, 220, 170);

        btn1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn1.setText("Save");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(770, 600, 150, 30);

        try {
            formattedtext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(formattedtext);
        formattedtext.setBounds(290, 350, 220, 30);

        l9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l9.setText("User Type");
        getContentPane().add(l9);
        l9.setBounds(630, 360, 93, 29);

        l10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        l10.setText("User Name");
        getContentPane().add(l10);
        l10.setBounds(630, 220, 93, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Admin", "Employee" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(780, 360, 150, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(770, 290, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banking/user22.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 50, 64, 60);

        setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "bankingdb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {



                String q1 = "insert into create_user value(?,?,?)";
                PreparedStatement mystatement1 = myconnection.prepareStatement(q1);
                mystatement1.setString(1, t1.getText());
                mystatement1.setString(2, jPasswordField1.getText());
                mystatement1.setString(3, jComboBox1.getSelectedItem().toString());
                mystatement1.execute();

                String q = "insert into user_info values(?,?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, t1.getText());
                mystatement.setString(2, t2.getText());
                if (r1.isSelected()) {
                    mystatement.setString(3, "Male");
                } else if (r2.isSelected()) {
                    mystatement.setString(3, "Female");
                }
                String dob = combobox3.getSelectedItem() + "/" + combobox2.getSelectedItem() + "/" + combobox1.getSelectedItem();
                mystatement.setString(4, dob);
                mystatement.setString(5, formattedtext.getText());
                mystatement.setString(6, textpane.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Submit Successfully");
                t1.setText(null);
                t2.setText(null);
                buttonGroup1.clearSelection();
                combobox1.setSelectedIndex(0);
                combobox2.setSelectedIndex(0);
                combobox3.setSelectedIndex(0);
                jComboBox1.setSelectedIndex(0);
                formattedtext.setText(null);
                jPasswordField1.setText("");
                textpane.setText(null);
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection" + e.getMessage());
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        for (int a = 1; a <= 31; a++) {
            combobox1.addItem(a);
        }
        for (int a = 1; a <= 12; a++) {
            combobox2.addItem(a);
        }
        for (int a = 1950; a <= 2000; a++) {
            combobox3.addItem(a);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combobox1;
    private javax.swing.JComboBox combobox2;
    private javax.swing.JComboBox combobox3;
    private javax.swing.JFormattedTextField formattedtext;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextPane textpane;
    // End of variables declaration//GEN-END:variables
}
